baseURL = "/rdkohalmy.github.io/"
languageCode = "en-us"
title = "Ryan '0ttrSpace' Kohalmy"
rssLimit = 20
copyright = "2022 Ryan Kohalmy All rights reserved"
minify = false

[Author]
  name = "Ryan Kohalmy"
  email = "rbkohalmy@outlook.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]